spring:
  application:
    name: spring_course_springboot
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

document-generation:
  port: 8081
  document-type: jobRegulation
  position: secretarySession
  urls:
    url-jobRegulation-secretarySession: http://localhost:${document-generation.port}/api/documents/v1/generation/${document-generation.document-type}/${document-generation.position}

server:
  port: 8080
