spring:
  application:
    name: spring_course_springboot
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: f,tkz17rd80htu41
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8080